### ISSUE TITLE
icon 

### ISSUE THREAD

**Issue by zhongzhong0505** [xianghongai/vscode-opened-editors#3]
![image](https://user-images.githubusercontent.com/15847574/117230023-b3134a00-ae4e-11eb-9cb5-2f4917156366.png)

**Comment by xianghongai** [comment]
Thank you for your feedback, I will fix this issue tonight. :)

**Comment by xianghongai** [comment]
![#3](https://user-images.githubusercontent.com/2075006/117324904-d2e45580-aec2-11eb-88db-76d1179bceb6.png)

Fixed, Closed.
